Neos:
  Neos:
    fusion:
      autoInclude:
        PSIT.NodeTypes: TRUE
    userInterface:
      translation:
        autoInclude:
          PSIT.NodeTypes:
            - Main
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        psit:
          position: 400
          label: 'PSIT'
          collapsed: FALSE
Carbon:
  IncludeAssets:
    Packages:
      'aa_PSIT.NodeTypes':
        Package: 'PSIT.NodeTypes'
        Path:
          Inline:
            CSS: 'Public/Frontend'
            JS: 'Public/Frontend'
          File:
            CSS: 'Public/Frontend'
            JS: 'Public/Frontend'
        General:
          Head:
            - timeline.css
          Body:
            - timeline.js
