Neos:
  Neos:
    fusion:
      autoInclude:
        PSIT.NodeTypes: TRUE
    userInterface:
      translation:
        autoInclude:
          PSIT.NodeTypes:
            - Main
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        psit:
          position: 400
          label: 'PSIT'
          collapsed: FALSE